baseurl = "/"
languageCode = "en-us"
title = "Igor Martins"
theme = "hugo-theme-nix"

[params]
  GithubID = "havok1305"
  TwitterID = "your_twitter"
  LinkedInID = "igor-martins-de-souza-58435b107"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "Igor_Martins"
  HeaderUsername = "igorms"
  HeaderHostname = "havok1305"
  Email = "havok1305@gmail.com"
  About = "Just another programmer"
  ProfilePicture = "http://chittagongit.com//images/nerd-icon-png/nerd-icon-png-8.jpg"
  GoogleAnalytics = "your_google_analytics_id"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
